server:
  ssl:
    key-alias: test
    key-store-password: 123456
    key-store: classpath:test.keystore
    enabled: true
    key-store-type: PKCS12
  port: 8081
logging:
  level:
    com:
      demo: debug
